# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [master, deploy]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Install and Deploy
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'yarn'
            - run: yarn install && yarn build:prod

            - name: deploy s3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --acl public-read --follow-symlinks --delete
              env:
                  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  SOURCE_DIR: 'build'

            - name: Invalidate CloudFront
              uses: chetan/invalidate-cloudfront-action@master
              env:
                  DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
                  PATHS: '/index.html'
              continue-on-error: true
